site_name: KluCoVa
site_description: 'PSTAT 234 (Spring 2021)'
site_author: 'Evgeny Noi'
repo_url: 'https://github.com/barguzin/klucova'
theme: 
  name: material
  palette: 
    primary: green
  #favicon: 'img/covid.ico'